
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://byemrekaya.github.io"

baseurl: /resumes

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Emre Kaya"
title: "{ Emre Kaya }"
description: "Blog and website of Emre KAYA, blogging mainly for tech. Opinions expressed are mine."
keywords: "emre kaya,angular,frontend developer,javascript developer,angular developer"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

# background-img: "../img/sitebg.jpg"


##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hello !! My name is Emre"
  - text: "I am a member of NG-Turkey."
  - text: "I like coding"
me-img: "/img/emre-kaya.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "emre kaya personel information"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/etiya.png"
    date: "May 2018 – Today"
    description: "I work in Product Development and Innovation in Fizz project. It has admin UI for managers, customer UI for customers and CSR UI for the call support team."
    stackText: "We are using the following technologies ;"
    technologies: [
      "Angular 7+ (up to current latest)",
      "State management with NGXS or NgRx",
      "Javascript (including latest ECMAScript)",
      "REST and GraphQL",
      "TypeScript",
      "RxJS",
      "Git",
      "Sass"]
  - image: "/img/timeline/etiya.png"
    date: "Dec 2017 – May 2018"
    description: "I work in the Software Solution Development department of the Telaura CRM Suite project. Telaura is an application that contains Telco CRM components. It was developed based on the BSS needs of a telecom operator."
    stackText: "We are using the following technologies ;"
    technologies: [
       "Oracle ADF",
       "Jdeveloper",
       "Oracle Database",
       "Toad",
       "Soa",
       "SoapUI",
       "The SIM module is designed to perform scheduled tasks in addition to the Telaura product, and the following technologies have been used to develop this module.",
       "Spring Framework (Cache Module, Cron Expression vb.)",
       "Oracle Database Advanced Queuing (AQ)",
       "In addition, I made 10 demo projects for the company's overseas presentations and then supported the fizz project as a full stack developer.",
       "PostgreSQL",
       "Angular JS",
       "Spring"]

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "byemrkaya@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Emre KAYA is an awesome person."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/byemrkaya"
  - title: "github"
    url: "https://github.com/byemrekaya"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: emrekaya
keybase-in-social: false
keybase-in-footer: false

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  # Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

# paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
